export const headlines = [
  "A wise philosopher once said ...",
  "Today let's reflect on...",
  "Today's Stoic wisdom...",
  "Let's take a moment and reflect...",
  "The wisdom of the ancients...",
  "Something to ponder 🤔...",
  "Words of wisdom...",
  "Reflect on this...",
  "Consider this thought...",
  "A moment of contemplation...",
  "Pause and think...",
  "Insights from the past...",
  "Reflecting on ancient wisdom...",
  "Timeless wisdom...",
  "Food for thought...",
  "Philosophical insights...",
  "A thought to consider...",
  "Ancient reflections...",
  "Ponder this wisdom...",
  "Let's reflect on wisdom...",
  "A moment for wisdom...",
  "Wisdom for today...",
  "Thoughts of the day 🧠...",
  "Reflect and grow...",
  "Ancient words, modern thoughts...",
  "Consider the wisdom...",
  "Moments of insight...",
  "Wisdom to live by...",
  "Daily dose of wisdom...",
  "Contemplate this 💭...",
  "Mindful reflections...",
];
