// Quotes.js
export const quotes = [
  "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
  "Wealth consists not in having great possessions, but in having few wants. - Epictetus",
  "He who fears death will never do anything worth of a man who is alive. - Seneca",
  "The best revenge is not to be like your enemy. - Marcus Aurelius",
  "First say to yourself what you would be; and then do what you have to do. - Epictetus",
  "The tranquility that comes when you stop caring what they say. Or think, or do. Only what you do. - Marcus Aurelius",
  "You have power over your mind - not outside events. Realize this, and you will find strength. - Marcus Aurelius",
  "The more we value things outside our control, the less control we have. - Epictetus",
  "Difficulties strengthen the mind, as labor does the body. - Seneca",
  "The obstacle is the way. - Marcus Aurelius",
  "If it is not right, do not do it, if it is not true, do not say it. - Marcus Aurelius",
  "We suffer more often in imagination than in reality. - Seneca",
  "Don't explain your philosophy. Embody it. - Epictetus",
  "Luck is what happens when preparation meets opportunity. - Seneca",
  "It is not the man who has too little, but the man who craves more, that is poor. - Seneca",
  "To be even-minded is the greatest virtue. - Heraclitus",
  "Begin at once to live, and count each separate day as a separate life. - Seneca",
  "No man is free who is not master of himself. - Epictetus",
  "How long are you going to wait before you demand the best for yourself? - Epictetus",
  "Waste no more time arguing about what a good man should be. Be one. - Marcus Aurelius",
  "He who has a why to live can bear almost any how. - Friedrich Nietzsche",
  "Circumstances don’t make the man, they only reveal him to himself. - Epictetus",
  "If you want to improve, be content to be thought foolish and stupid. - Epictetus",
  "To be calm is the highest achievement of the self. - Zen Proverb",
  "Life is very short and anxious for those who forget the past, neglect the present, and fear the future. - Seneca",
  "Wealth consists not in having great possessions, but in having few wants. - Epictetus",
  "It is the power of the mind to be unconquerable. - Seneca",
  "The mind that is anxious about future events is miserable. - Seneca",
  "What man actually needs is not a tensionless state but rather the striving and struggling for a worthwhile goal. - Viktor Frankl",
  "The more we value things outside our control, the less control we have. - Epictetus",
  "The soul becomes dyed with the color of its thoughts. - Marcus Aurelius",
  "He who fears death will never do anything worth of a man who is alive. - Seneca",
  "Man conquers the world by conquering himself. - Zeno of Citium",
  "It is the nature of the wise to resist pleasures, but the foolish to be a slave to them. - Epictetus",
  "No man is free who is not master of himself. - Epictetus",
  "The best revenge is not to be like your enemy. - Marcus Aurelius",
  "The key is to keep company only with people who uplift you, whose presence calls forth your best. - Epictetus",
  "Very little is needed to make a happy life; it is all within yourself, in your way of thinking. - Marcus Aurelius",
  "He who is brave is free. - Seneca",
  "If you want to improve, be content to be thought foolish and stupid. - Epictetus",
  "No great thing is created suddenly. - Epictetus",
  "To bear trials with a calm mind robs misfortune of its strength and burden. - Seneca",
  "It does not matter what you bear, but how you bear it. - Seneca",
  "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control. - Epictetus",
  "To live a good life: We have the potential for it. If we learn to be indifferent to what makes no difference. - Marcus Aurelius",
  "It is not the man who has too little, but the man who craves more, that is poor. - Seneca",
  "Wealth consists not in having great possessions, but in having few wants. - Epictetus",
  "How long are you going to wait before you demand the best for yourself? - Epictetus",
  "Luck is what happens when preparation meets opportunity. - Seneca",
  "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
  "Man is disturbed not by things, but by the views he takes of them. - Epictetus",
  "Begin at once to live, and count each separate day as a separate life. - Seneca",
  "To be even-minded is the greatest virtue. - Heraclitus",
];
